### ISSUE TITLE
Preparation of Navbar's component

### ISSUE THREAD

**Issue by mkaramuk** [quikkom/quikkom-frontend#2]
![Navbar component preview](https://github.com/quikkom/quikkom-frontend/assets/39464118/27bf682d-e408-4671-b1d6-22721d3a6cf8)

- [x] There will be a logo on the top left side. 
- [ ] The search box should be autocomplete type. It should list categories, products or stores according to the data entered. (This part can be passed using static data until the backend is ready).
- [x] It is enough to add the cart button as a link as in the image.
- [ ] Login button should be added as a button as in the image.

**Comment by TalhaAksoy** [comment]
#7 2 task finished this pull request

**Comment by mkaramuk** [comment]
We've got a new design. I sent it to you @TalhaAksoy

**Comment by mkaramuk** [comment]
Design is completely changed. This issue won't be done.
